project:
  type: website
  output-dir: docs

website:
  title: "BYUI AI Tutor"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/BYUIDSconsulting/ai-chatbot_W25

format:
  html:
    theme: slate
    css: styles.css



